
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alumno
 */
public class Asistencia extends javax.swing.JFrame {
     private static final String driver="com.mysql.jdbc.Driver";
    private static final String user="root";
    private static final String pass=("");
    private static final String url=("jdbc:mysql://localhost:3306/proyecto-bd");
    
    int se1,se2,se3,se4,se5,se6,se7,se8,se9,se10,se11,se12;
    
    
    
    /**
     * Creates new form Asistencia
     */
    public Asistencia() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.getContentPane().setBackground(Color.decode("#00bfff"));
        this.setTitle("Control de tutorias");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtnoDeLista = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        chk2 = new javax.swing.JCheckBox();
        etinombre = new javax.swing.JLabel();
        chk3 = new javax.swing.JCheckBox();
        chk5 = new javax.swing.JCheckBox();
        chk4 = new javax.swing.JCheckBox();
        chk6 = new javax.swing.JCheckBox();
        chk7 = new javax.swing.JCheckBox();
        chk8 = new javax.swing.JCheckBox();
        chk9 = new javax.swing.JCheckBox();
        chk10 = new javax.swing.JCheckBox();
        chk1 = new javax.swing.JCheckBox();
        chk11 = new javax.swing.JCheckBox();
        chk12 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtnoDeLista.setText(" ");

        jLabel1.setText("Numero de lista");

        jButton1.setText("buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chk2.setText("semana 2");

        etinombre.setText(" ");

        chk3.setText("semana 3");

        chk5.setText(" semana 5");
        chk5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk5ActionPerformed(evt);
            }
        });

        chk4.setText("semana 4");

        chk6.setText("semana 6");

        chk7.setText("semana 7");

        chk8.setText("semana 8");

        chk9.setText("semana 9");

        chk10.setText("semana 10");

        chk1.setText("semana 1");

        chk11.setText("semana 11");

        chk12.setText("semana 12");
        chk12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk12ActionPerformed(evt);
            }
        });

        jButton2.setText("registrar asistencia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 102, 102));

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setText("cambiar de usuario");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setText("Modificar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(etinombre, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnoDeLista, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chk9)
                                    .addComponent(chk5)
                                    .addComponent(chk1))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chk10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(chk6))
                                    .addComponent(chk2))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(chk11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(chk3)
                                    .addComponent(chk7))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chk12)
                                    .addComponent(chk8)
                                    .addComponent(chk4)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnoDeLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etinombre))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk2)
                    .addComponent(chk3)
                    .addComponent(chk4)
                    .addComponent(chk1))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk5)
                    .addComponent(chk6)
                    .addComponent(chk7)
                    .addComponent(chk8))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk9)
                    .addComponent(chk10)
                    .addComponent(chk11)
                    .addComponent(chk12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try{                                         
           
            Connection conn = (Connection) DriverManager.getConnection(url, user, pass);
            
            PreparedStatement pps = conn.prepareStatement("select * from alumnos where noDeLista = ?");
            pps.setString(1, txtnoDeLista.getText().trim());
            ResultSet rs = pps.executeQuery();
                if(rs.next())
                {
                etinombre.setText(rs.getString("nombre"));
                }
                else{
                JOptionPane.showMessageDialog(null, "no existe ese numero de lista");
                }
            
        }catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chk5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk5ActionPerformed

    private void chk12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try{              
            
           if(chk1.isSelected()){
                    se1 =1;
               }else{
                   se1=0;
               }
               if(chk2.isSelected()){
                    se2 =1;
               }else{
                   se2=0;
               }
               if(chk3.isSelected()){
                    se3 =1;
               }else{
                   se3=0;}
               if(chk4.isSelected()){
                    se4 =1;
               }else{
                   se4=0;
               }
               if(chk5.isSelected()){
                    se5 =1;
               }else{
                   se5=0;
               }
        if(chk6.isSelected()){
                   se6 =1;
               }else{
                   se6=0;
               }
        if(chk7.isSelected()){
                    se7 =1;
               }else{
                   se7=0;
               }
        if(chk8.isSelected()){
                    se8 =1;
               }else{
                   se8=0;
               }
        if(chk9.isSelected()){
                    se9 =1;
               }else{
                   se9=0;
               }
        if(chk10.isSelected()){
                    se10 =1;
               }else{
                   se10=0;
               }
        if(chk11.isSelected()){
                    se11 =1;
               }else{
                   se11=0;
               }
        if(chk12.isSelected()){
                    se12 =1;
               }else{
                   se12=0;
               }
               
           
            Connection conn = (Connection) DriverManager.getConnection(url, user, pass);
             PreparedStatement pps = conn.prepareStatement("insert into asistencia (noDeLista,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pps.setString(1, txtnoDeLista.getText().trim());
            pps.setString(2, ""+se1);
            pps.setString(3, ""+se2);
            pps.setString(4, ""+se3);
            pps.setString(5, ""+se4);
            pps.setString(6, ""+se5);
            pps.setString(7, ""+se6);
            pps.setString(8, ""+se7);
            pps.setString(9, ""+se8);
            pps.setString(10, ""+se9);
            pps.setString(11, ""+se10);
            pps.setString(12, ""+se11);
            pps.setString(13, ""+se12);
           
            pps.executeUpdate();
            txtnoDeLista.setText("");
            JOptionPane.showMessageDialog(null, "Datos guardados exitosamente");
          }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Datos incorrectos / Faltantes\n"+ex);
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Inicio nF=new Inicio();
        nF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ControlUsuarios nF=new ControlUsuarios();
        nF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //  

        if(chk1.isSelected()){
                    se1 =1;
               }else{
                   se1=0;
               }
               if(chk2.isSelected()){
                    se2 =1;
               }else{
                   se2=0;
               }
               if(chk3.isSelected()){
                    se3 =1;
               }else{
                   se3=0;}
               if(chk4.isSelected()){
                    se4 =1;
               }else{
                   se4=0;
               }
               if(chk5.isSelected()){
                    se5 =1;
               }else{
                   se5=0;
               }
        if(chk6.isSelected()){
                   se6 =1;
               }else{
                   se6=0;
               }
        if(chk7.isSelected()){
                    se7 =1;
               }else{
                   se7=0;
               }
        if(chk8.isSelected()){
                    se8 =1;
               }else{
                   se8=0;
               }
        if(chk9.isSelected()){
                    se9 =1;
               }else{
                   se9=0;
               }
        if(chk10.isSelected()){
                    se10 =1;
               }else{
                   se10=0;
               }
        if(chk11.isSelected()){
                    se11 =1;
               }else{
                   se11=0;
               }
        if(chk12.isSelected()){
                    se12 =1;
               }else{
                   se12=0;
               }
        try{
         Connection conn = (Connection) DriverManager.getConnection(url, user, pass);
         PreparedStatement pps = conn.prepareStatement("update asistencia set  s1 = ?, s2 = ?, s3 = ?, s4 = ?, s5 = ?, s6 = ?, s7 = ?, s8 = ?, s9 = ?, s10 = ?, s11 = ?, s12 = ? where noDeLista = "+txtnoDeLista.getText().trim());    
            
            pps.setString(1, ""+se1);
            pps.setString(2, ""+se2);
            pps.setString(3, ""+se3);
            pps.setString(4, ""+se4);
            pps.setString(5, ""+se5);
            pps.setString(6, ""+se6);
            pps.setString(7, ""+se7);
            pps.setString(8, ""+se8);
            pps.setString(9, ""+se9);
            pps.setString(10, ""+se10);
            pps.setString(11, ""+se11);
            pps.setString(12, ""+se12);
           
            pps.executeUpdate();
            txtnoDeLista.setText("");
            JOptionPane.showMessageDialog(null, "Datos Modificados exitosamente");
          }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"la modificacion fallo: Datos incorrectos / Faltantes\n"+ex);
            
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asistencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asistencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk10;
    private javax.swing.JCheckBox chk11;
    private javax.swing.JCheckBox chk12;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JCheckBox chk5;
    private javax.swing.JCheckBox chk6;
    private javax.swing.JCheckBox chk7;
    private javax.swing.JCheckBox chk8;
    private javax.swing.JCheckBox chk9;
    private javax.swing.JLabel etinombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtnoDeLista;
    // End of variables declaration//GEN-END:variables
}
