
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Isaac
 */
public class inicioUsuario extends javax.swing.JFrame {
    private static final String driver="com.mysql.jdbc.Driver";
    private static final String user="root";
    private static final String pass=("");
    private static final String url=("jdbc:mysql://localhost:3306/proyecto-bd");
    /**
     * Creates new form inicioUsuario
     */
    public inicioUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.getContentPane().setBackground(Color.decode("#66ffcc"));
        this.setTitle("Alumnos / Control de tutorias");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("ASISTENCIA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tabla.setBackground(new java.awt.Color(60, 186, 125));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton2.setText("ALUMNOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setText("cambiar de usuario");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText("SITUACION ACADEMICA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("ACTIVIDADES");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton2)
                        .addGap(77, 77, 77)
                        .addComponent(jButton1)
                        .addGap(40, 40, 40)
                        .addComponent(jButton3)
                        .addGap(53, 53, 53)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton5)))
                .addContainerGap(347, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
        Connection conn;
    try {
        conn = (Connection) DriverManager.getConnection(url, user, pass);
        String sql ="Select * from asistencia";
        Statement st;
        DefaultTableModel model = new DefaultTableModel();
        String[] dato = new String[13];
        model.addColumn("no De lista");
        model.addColumn("semana 1");
        model.addColumn("semana 2");
        model.addColumn("semana 3");
        model.addColumn("semana 4");
        model.addColumn("semana 5");
        model.addColumn("semana 6");
        model.addColumn("semana 7");
        model.addColumn("semana 8");
        model.addColumn("semana 9");
        model.addColumn("semana 10");
        model.addColumn("semana 11");
        model.addColumn("semana 12");
        model.addRow(dato);
        
        tabla.setModel(model);
         
        
        st = conn.createStatement();
        
        ResultSet result = st.executeQuery(sql);
        
        while(result.next()){
            dato[0]=result.getString(1);
            dato[1]=result.getString(2);
            dato[2]=result.getString(3);
            dato[3]=result.getString(4);
            dato[4]=result.getString(5);
            dato[5]=result.getString(6);
            dato[6]=result.getString(7);
            dato[7]=result.getString(8);
            dato[8]=result.getString(9);
            dato[9]=result.getString(10);
            dato[10]=result.getString(11);
            dato[11]=result.getString(12);
            dato[12]=result.getString(13);
            
            model.addRow(dato);
        }
                
        
    } catch (SQLException ex) {
        Logger.getLogger(inicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
    }
        
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection conn;
    try {
        conn = (Connection) DriverManager.getConnection(url, user, pass);
        String sql ="Select * from alumnos";
        Statement st;
        DefaultTableModel model = new DefaultTableModel();
        String[] dato = new String[11];
        model.addColumn("no De lista");
        model.addColumn("nombre");
        model.addColumn("edad");
        model.addColumn("nacimiento");
        model.addColumn("sexo");
        model.addColumn("direccion");
        model.addColumn("colonia");
        model.addColumn("C.P.");
        model.addColumn("Edo. civil");
        model.addColumn("Telefono");
        model.addColumn("e-mail");
        
        model.addRow(dato);
        
        tabla.setModel(model);
         
        
        st = conn.createStatement();
        
        ResultSet result = st.executeQuery(sql);
        
        
        while(result.next()){
            dato[0]=result.getString(1);
            dato[1]=result.getString(2);
            dato[2]=result.getString(3);
            dato[3]=result.getString(4);
            dato[4]=result.getString(5);
            dato[5]=result.getString(6);
            dato[6]=result.getString(7);
            dato[7]=result.getString(8);
            dato[8]=result.getString(9);
            dato[9]=result.getString(10);
            dato[10]=result.getString(11);
            
            
            model.addRow(dato);
        }
                
        
    } catch (SQLException ex) {
        Logger.getLogger(inicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Tendra que volver a iniciar sesion");
        ControlUsuarios nF=new ControlUsuarios();
        nF.setVisible(true);
       
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn;
    try {
        conn = (Connection) DriverManager.getConnection(url, user, pass);
        String sql ="Select * from materias";
        Statement st;
        DefaultTableModel model = new DefaultTableModel();
        String[] dato = new String[4];
        model.addColumn("Identificador de la materia");
        model.addColumn("No de lista");
        model.addColumn("materia");
        model.addColumn("¿Aprobo?");
        
        model.addRow(dato);
        
        tabla.setModel(model);
         
        
        st = conn.createStatement();
        
        ResultSet result = st.executeQuery(sql);
        
        while(result.next()){
            dato[0]=result.getString(1);
            dato[1]=result.getString(2);
            dato[2]=result.getString(3);
            dato[3]=result.getString(4);
            
            
            model.addRow(dato);
        }
        } catch (SQLException ex) {
        Logger.getLogger(inicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Connection conn;
    try {
        conn = (Connection) DriverManager.getConnection(url, user, pass);
        String sql ="Select * from actividades";
        Statement st;
        DefaultTableModel model = new DefaultTableModel();
        String[] dato = new String[3];
        model.addColumn("Numero de la actividad");
        model.addColumn("Nombre");
        model.addColumn("Estado");
        
        
        model.addRow(dato);
        
        tabla.setModel(model);
         
        
        st = conn.createStatement();
        
        ResultSet result = st.executeQuery(sql);
        
        while(result.next()){
            dato[0]=result.getString(1);
            dato[1]=result.getString(2);
            dato[2]=result.getString(3);
            
            
            
            model.addRow(dato);
        }
        } catch (SQLException ex) {
        Logger.getLogger(inicioUsuario.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
