



import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alumno
 */
public class Materias extends javax.swing.JFrame {
 private static final String driver="com.mysql.jdbc.Driver";
    private static final String user="root";
    private static final String pass=("");
    private static final String url=("jdbc:mysql://localhost:3306/proyecto-bd");
    /**
     * Creates new form Materias
     */
    public Materias() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.getContentPane().setBackground(Color.decode("#00bfff"));
        this.setTitle("Control de tutorias");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        txtnoDeLista = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        etinombre = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setText("cambiar de usuario");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 6, -1, 20));

        txtnoDeLista.setText(" ");
        getContentPane().add(txtnoDeLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 36, 218, -1));

        jLabel1.setText("Numero de lista");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jButton1.setText("buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 32, 76, -1));

        etinombre.setText(" ");
        getContentPane().add(etinombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 88, 327, -1));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 6, -1, 20));

        jButton2.setText("Registrar materias");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        ControlUsuarios nF=new ControlUsuarios();
        nF.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try{                                         
           
            Connection conn = (Connection) DriverManager.getConnection(url, user, pass);
            
            PreparedStatement pps = conn.prepareStatement("select * from alumnos where noDeLista = ?");
            pps.setString(1, txtnoDeLista.getText().trim());
            ResultSet rs = pps.executeQuery();
                if(rs.next())
                {
                etinombre.setText(rs.getString("nombre"));
                }
                else{
                JOptionPane.showConfirmDialog(null, "no existe ese id");
                }
            
        }catch(Exception ex){
            System.out.println(ex);
            
        }        try{

            Connection conn = (Connection) DriverManager.getConnection(url, user, pass);

            PreparedStatement pps = conn.prepareStatement("select * from alumnos where noDeLista = ?");
            pps.setString(1, txtnoDeLista.getText().trim());
            ResultSet rs = pps.executeQuery();
            if(rs.next())
            {
                etinombre.setText(rs.getString("nombre"));
            }
            else{
                JOptionPane.showConfirmDialog(null, "no existe ese id");
            }

        }catch(Exception ex){
            System.out.println(ex);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Inicio nF=new Inicio();
        nF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String materia=JOptionPane.showInputDialog(null,"Ingrese el nombre de la materia");
        int aux=JOptionPane.showConfirmDialog(null, "¿Aprobo?");
        if(aux==JOptionPane.OK_OPTION){
            Connection conn;
            try {
                conn = (Connection) DriverManager.getConnection(url, user, pass);
                PreparedStatement pps = conn.prepareStatement("insert into materias (ID,noDeLista,materia,aprobada) VALUES (?,?,?,?)");
            pps.setString(1, "0");
            pps.setString(2, txtnoDeLista.getText().trim());
            pps.setString(3, materia);
            pps.setString(4, "si");
            pps.executeUpdate();
            } catch(Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
             
        }
        else if(aux==JOptionPane.NO_OPTION){
              Connection conn;
            try {
                conn = (Connection) DriverManager.getConnection(url, user, pass);
                PreparedStatement pps = conn.prepareStatement("insert into materias (ID,noDeLista,materia,aprobada) VALUES (?,?,?,?)");
            pps.setString(1, "0");
            pps.setString(2, txtnoDeLista.getText().trim());
            pps.setString(3, materia);
            pps.setString(4, "no");
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Datos guardados exitosamente");
            txtnoDeLista.setText("");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "salio del registro");
        }
            
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Materias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Materias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etinombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtnoDeLista;
    // End of variables declaration//GEN-END:variables
}
